### ISSUE TITLE
Table entries merging

### ISSUE THREAD

**Issue by micahjames** [kota7/striprtf#2]
Greetings!

I just found striprtf today and it very nearly solves a problem I've been trying to solve on my own for the last several days. There was one thing getting in my way, though. I need to be able to extract data from tables in these rtf files. Right now, the output of read_rtf is simply the concatenation of all of the cells of a given table with no indication of where one entry ends and the next begins. For instance, if the following table were in an rtf document 

| A  | B | C |
| ------------- | ------------- | ------------- |
| 1.01 | 2.02 | 3. 03|

then the output of read_rtf would be:

    [1]  "ABC1.012.023.03"  ""

However, if you added `cell` and `row` to the `keys` vector in .specialchars in global.R with corresponding values `x0009` and `x000A` in the `hexstr` vector, and `\t` and `\n` in the `str` vector, then the same table would output as 

      [1] "A\tB\tC" "1.01\t2.02\t3.03" ""

In case it is helpful, I'm attaching an rtf with this table.

Thanks so much for writing this package. I couldn't believe my luck today!

-Micah

[table.rtf.zip](https://github.com/kota7/striprtf/files/998403/table.rtf.zip)

**Comment by kota7** [comment]
Hi Micah,  thank you for using the package, and for the helpful suggestion.  This table format aspect is something that I did not even know.  

I will have a look and add this feature in a few days.  I guess your suggestion would work well.

**Comment by kota7** [comment]
Hi, updated version (v.0.4.1) has been loaded to the master branch.  I would like you to try it.  Since it is not on CRAN yet, please install by:

```{r}
devtools::install_github("kota7/striprtf")
```

Let me know if you have any trouble with the installation.

This version parse tables specially with user-defined row_start, row_end, cell_end indicators.  You may set `cell_end="\t"` to make tables tab-separated (with an extra at the end).  `row_start` option, I believe, is convenient if you have a large document with many tables, since it allows you to identify where are the tables.
By the way, you don't need to set `row_end="\n"` since rows are automatically separated.

I hope you like this.  Please let me know your questions, comments or complaints, if any.

**Comment by micahjames** [comment]
I was able to install the new version without problem and it works perfectly for my purposes. Thank you so much for making the changes!

**Comment by kota7** [comment]
Not at all.  I will notice here when new version is uploaded to CRAN, then close this.
It may take a few days since I need to do some bug fix for other issues.

Thank

**Comment by kota7** [comment]
Now on CRAN (v.0.4.3).
